on:
  issues:
    types: [opened, edited]
jobs:
  check-issue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Check Issue title
        run: |
          echo "ISSUE_TITLE_VALID=$(echo '${{ github.event.issue.title }}' | bash title.sh)" >> $GITHUB_ENV

      - name: Check Issue body
        run: |
          echo "ISSUE_BODY_VALID=$(echo '${{ github.event.issue.body }}' | bash body.sh)" >> $GITHUB_ENV

      - name: debug
        run: |
          echo "${{ env.ISSUE_BODY_VALID }}"

      - name: Create comment
        uses: peter-evans/create-or-update-comment@v2
        if: ${{ env.ISSUE_BODY_VALID != 'true' }}
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            Пожалуйста, используйте шаблон для баг-репорта

            Заголовок: `Bug: заголовок`

            ```markdown
            ## Summary

            Короткое описание ошибки

            ## Environment

            Ссылка на билд/коммит/версия ПО и всего окружения

            ## Steps to reproduce

            Полный перечень шагов для воспроизведения

            ## Expected result

            Какой результат должен был быть без ошибки

            ## Actual result

            Какой результат получился на самом деле
            ```

      - name: Close Issue
        if: ${{ env.ISSUE_BODY_VALID == 'true' }}
        uses: peter-evans/close-issue@v2
        with:
          comment: |
            Баг-репорт корректный. Успешно закрыто!
